automatically decode json requests and pass to command result
Simovative/zeus pull request #38
Opened 2020-09-23 09:53 UTC by slider1337

- introduce factory for creating http request (BC-Break!)
- automatically decode json requests and put it in the command request

ACFIVE-27888

2020-09-23 10:18 UTC, Carpenter0100 requested changes

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/Json/JsonEncodingService.php
> +final class JsonEncodingService implements JsonEncodingServiceInterface {
haha nice

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +		return new JsonEncodingService();
inject JsonEncodingService

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +		return ($contentType === self::CONTENT_TYPE_JSON);
klammern sind unnötig

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +			case 'HEADER':
Wat isn Header? Muss das nicht HEAD sein?

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +			case 'HEADER':
Brauchen wir das überhaupt?

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +				return new HttpPostRequest($currentUrl, $_REQUEST, $_SERVER, $parsedBody, $uploadedFiles);
theoretisch müssen die uploadedFiles auch in PATCH und PUT rein.

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +		if ($this->isJsonContent($serverParameters)) {
wenn es kein json ist kann ich das weiterhin nur 1 mal holen?

2020-09-23 10:18 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +				true
assoc true darf eigentlich nicht sein.

2020-09-23 10:52 UTC, slider1337 commented on src/Http/HttpRequestFactory.php
> +		if ($this->isJsonContent($serverParameters)) {
ja, weil man nen input stream nicht rewinden kann, man könnte den höchstens local buffern. alternativ könnte ich ihn abrufen, wenn ich das in den commandRequest packe.

2020-09-23 10:53 UTC, slider1337 commented on src/Http/HttpRequestFactory.php
> +				return new HttpPostRequest($currentUrl, $_REQUEST, $_SERVER, $parsedBody, $uploadedFiles);
hmm ich denke da wird das eher nicht benutzt. mir fällt aktuell zumindest kein fall ein.

2020-09-23 10:55 UTC, Carpenter0100 commented on src/Http/HttpRequestFactory.php
> +		if ($this->isJsonContent($serverParameters)) {
sollte nicht sein finde ich. egal ob json oder nit, sollte ich die parameter holen können so oft wie ich will.

2020-09-23 10:57 UTC, slider1337 commented on src/Http/HttpRequestFactory.php
> +			case 'HEADER':
HEAD hast du recht, habs angepasst. aktuell wird es nicht benutzt, aber macht prinzipiell sinn für einige anwendungsfälle. Der Option Request fehlt auch noch, der ist vor allem für CORS wichtig.

2020-09-23 14:49 UTC, slider1337 commented on src/Http/HttpRequestFactory.php
> +		return new JsonEncodingService();
habs umgeschrieben, kommt jetzt aus der master factory und kann somit auch sonst in der application benutzt werden. inject macht hier keinen sinn, weil wir im di container sind

2020-09-24 08:56 UTC, Carpenter0100 approved these changes

2020-09-24 09:26 UTC, merged