ACFIVE-32665
Simovative/zeus pull request #60
Opened 2021-07-22 13:01 UTC by slider1337

REST: PSR-Handler in Zeus richtig einbauen

- correct handling of psr request
- set way for implementing middleware etc.
- be more psr compatible

2021-07-23 10:25 UTC, Carpenter0100 requested changes
Also, alles in allem finde ich die Umsetzung nicht gut gelungen. Ich hätte es vermutlich ganz anders gemacht.
Können wir später nochmal drüber reden.

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Command/CommandDispatcher.php
> +        if (null === $validationResult || $validationResult->isValid()) {
die inline kommentare sind hier nicht nötig. 
es wäre gut wenn du das if else konstrukt hier ein bisschen aufräumst. Also nach dem Prinzip so schnell wie möglich aus der Methode raus.

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Handler/HandlerRouterChain.php
> +        return null;
warum return null? Könnte man das nicht drin lassen und die Exception abfangen und dann die router chain weiter durchlaufen?

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Http/HttpKernel.php
> +                throw new RouteNotFoundException($request->getUrl());
Der Dispatcher sollte diese Exception nicht werfen. Das ist teil des routings.

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Http/HttpKernel.php
> +        $psrRequest = ServerRequest::fromGlobals();
Nutz hier am besten ne ServerRequestFactory

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Http/Request/HttpRequestDispatcherLocator.php
> +        if ($route->isPsrRoute()) {
kann eine psr route nicht auch ein get sein? Oder wie ist die Unterscheidung hier?

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Http/Routing/HttpRouter.php
> +    private function createRouteParameterMap(UriInterface $uri): HandlerRouteParameterMapInterface {
PSR

2021-07-23 10:25 UTC, Carpenter0100 commented on src/Http/Routing/HttpRouter.php
> +        // Route not found
Warum keine Exception?

2021-07-26 06:26 UTC, slider1337 commented on src/Handler/HandlerRouterChain.php
> +        return null;
Macht für mich keinen Sinn bei allen drei chains ein try catch drum rum zu basteln, aber ich pack das wie besprochen in den router

2021-07-26 06:35 UTC, slider1337 commented on src/Http/Request/HttpRequestDispatcherLocator.php
> +        if ($route->isPsrRoute()) {
N des betrifft die alten zeus routen die waren unterteilt auf get und post, psr kann alles sein

2021-07-27 14:02 UTC, obi-wan-tobi approved these changes, later dismissed

2021-07-28 11:21 UTC, obi-wan-tobi approved these changes

2021-08-02 12:27 UTC, Carpenter0100 approved these changes

2021-08-02 12:29 UTC, merged